### ISSUE TITLE
Crash on run. Message on game "199X: A Game Without Mechanics"

### ISSUE THREAD

**Issue by ErnestoD** [Codeusa/SteamCleaner#40]
"Message": "Could not find a part of the path 'C:\Program Files (x86)\Steam\SteamApps\common\199X.dd.symlink'."
[UnhandledException_10-16-2016.txt](https://github.com/Codeusa/SteamCleaner/files/531948/UnhandledException_10-16-2016.txt)

**Comment by Codeusa** [comment]
Fixed in the next release

**Comment by ErnestoD** [comment]
Gave it another try still crashing. Here is the log.

Ernesto B. Delacruz, Jr.
706-452-3060
ernesto.b.delacruz.jr@gmail.com
