### ISSUE TITLE
Resizeable application, Separate fields for File, App and Path, Options menu

### ISSUE THREAD

**Issue by KIPdeKIP** [Codeusa/SteamCleaner#5]
I'd like to see which apps have files that can be deleted. Either through the name of the app or a full / relative path.

In the case of a relative path the drive letter / name should also be shown.

**Comment by KIPdeKIP** [comment]
As a heads up, the name of apps and the folders they own are saved in the `appmanifest_<appid>.acf` files in the `steamapps` folder.

**Comment by Codeusa** [comment]
Added

**Comment by KIPdeKIP** [comment]
Working, sort of.

http://i.imgur.com/R2sc2kK.png

The full path is too long to fit in the application. The application should be made re-sizable.

**Comment by Codeusa** [comment]
Resolved

**Comment by Fazer2** [comment]
The application is still not resizable for me in version 1.1.
